### PR TITLE
Feature mempoke

### PR DESCRIPTION
**Pull request by adam-dej**
Memory poker feature. Contains framework for defining peripherals and several peripherals of STM32F0 MCU.

[Review on Reviewable](https://reviewable.io/reviews/fmfi-svt-deadlock/hw-testing/1)

### CODE REVIEW

**Comment by AnotherKamila** [comment]
Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[mempoke.py, line 10 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fMcb1EFFdtcABw4ks:-K7fMcb1EFFdtcABw4kt:-545811519) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L10)):_
Why is this necessary? Disconnects from GDB or something?

---

_[mempoke.py, line 20 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fNbJ9dxWLjgnHOq8t:-K7fNbJ9dxWLjgnHOq8u:444367390) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L20)):_
Move these two inside `class T` and use `T.CODE`/`T.LENGTH`. Also, "code" is a terrible word... but I don't have a better one, so whatever.

---

_[mempoke.py, line 23 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fNsk7GVSEG_sh-7Qt:-K7fNsk7GVSEG_sh-7Qu:2054952338) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L23)):_
Move this above `DeviceMemory` -- this needs to be seen before that.

---

_[mempoke.py, line 34 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fOMVewQpwWY7O4eBS:-K7fOMVewQpwWY7O4eBT:327812400) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L34)):_
Move inside `MMPeripheral`.

---

_[mempoke.py, line 43 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fOi2_Mt669JlgK_Bw:-K7fOi2_Mt669JlgK_Bx:-1697162068) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L43)):_
`device_memory` actually doesn't have to be just device memory (`DummyMemory`?) -- I'd suggest `s/device_memory/memory/g`.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by adam-dej** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[mempoke.py, line 20 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fNbJ9dxWLjgnHOq8t:-K7famItZwK6nagukTl-:-752807732) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L20)):_
CODE: I'll use FORMAT_CHAR then.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[mempoke.py, line 10 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fMcb1EFFdtcABw4ks:-K7fW24Bq5PvvsIfPq9x:-1588038848) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L10)):_
Just unbinds the `inferior` variable explicitly. At the time of writing I wasn't really sure what is this gonna be used for and intensive testing was one of the things that came to my mind. So I thought it might be a good idea to clean it up when we're sure we don't need it anymore, but I think that removing it wouldn't cause any real harm.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by adam-dej** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[mempoke.py, line 23 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fNsk7GVSEG_sh-7Qt:-K7fdVsVY98U4f4PCczg:-499146009) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L23)):_
Done.

---

_[mempoke.py, line 34 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fOMVewQpwWY7O4eBS:-K7fdXXothWeXLydGh1U:-499146009) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L34)):_
Done.

---

_[mempoke.py, line 43 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fOi2_Mt669JlgK_Bw:-K7fdYlwTcmHJvRMNJZE:-499146009) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L43)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by AnotherKamila** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[mempoke.py, line 10 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fMcb1EFFdtcABw4ks:-K7fdhjdImcZmx4hffSN:1107935571) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L10)):_
I don't think there's any point -- I'd remove it.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by lubo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[mempoke.py, line 1 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fe5bTbqCbQ34dcK28:-K7fe5bTbqCbQ34dcK29:1525955490) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L1)):_
Why is this commented out ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by adam-dej** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[mempoke.py, line 1 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fe5bTbqCbQ34dcK28:-K7ff-id5EnTs42_T6tu:2141288534) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L1)):_
Uh, my bad.
Forgot to un-comment after testing.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by lubo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[mempoke.py, line 10 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fMcb1EFFdtcABw4ks:-K7fgGwH5N1sW5HclF_V:-351451923) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L10)):_
Removed in 6a331c4.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by adam-dej** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[mempoke.py, line 1 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fe5bTbqCbQ34dcK28:-K7fjGvt-_mvo5zeNQ46:-499146009) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L1)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by lubo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[mempoke.py, line 1 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fe5bTbqCbQ34dcK28:-K7fjr7giXjAyQtDFwYW:1631664431) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L1)):_
Seems like you've reverted my changes from 6a331c4 in fa68b1d4fd98a040418d98f7f37e799cbf477ac1.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by adam-dej** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[mempoke.py, line 1 [r2]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1#-K7fe5bTbqCbQ34dcK28:-K7flyqoPTSk65DKW8bI:-497468049) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/a2acfd8f5aa5248aede0b6bea7ecdfd5a0d992c1/mempoke.py#L1)):_
Fixed

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/1)_

**Pull request merged**
