### PR TITLE
Feature testseq

### PR DESCRIPTION
**Pull request by adam-dej**
Test sequencer

[Review on Reviewable](https://reviewable.io/reviews/fmfi-svt-deadlock/hw-testing/2)

### CODE REVIEW

**Comment by lubo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[test_sequencer.py, line 49 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lKLDhLGZrLTets9dB:-K7lKLDi3VmgFDELRbuE:1344877568) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L49)):_
This line can be simplified to `answer.strip().upper() == 'Y'`.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by lubo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[test_sequencer.py, line 12 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lLavFeLYmSjTlY_FT:-K7lLavFeLYmSjTlY_FU:-115134344) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L12)):_
This line shadows built-in name '[filter](https://docs.python.org/3/library/functions.html#filter)'.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by AnotherKamila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[test_sequencer.py, line 12 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lLavFeLYmSjTlY_FT:-K7lU264DuhGQ-Z6sLll:-1748900598) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L12)):_
Which is not necessarily a problem -- but anyway, in this case I'd rename it to `selected_tests` or something.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by AnotherKamila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[test_sequencer.py, line 47 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lUzVYVIWZ77dg9e-V:-K7lUzVYVIWZ77dg9e-W:1520290529) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L47)):_
simplify: `if answer.strip().upper() in ['Y', 'N']:`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by AnotherKamila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

_[test_sequencer.py, line 10 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lVHZTI8B0NUz0ioM9:-K7lVHZUSiP-a8QVEfN9:-1626509078) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L10)):_
Docstrings should conform to the standard format:

``` python
"""One-line docstring (full sentence, with a period)."""

"""Longer docstrings: start with a one-line summary.

After a blank line, continue with a more detailed description.
"""
```

---

_[test_sequencer.py, line 13 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lVpXzijdMunjwvmfk:-K7lVpXzijdMunjwvmfl:1602382297) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L13)):_
IIRC, can be simplified to just `if filter:`.

---

_[test_sequencer.py, line 18 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lW3X5boybOmezyIFk:-K7lW3X67S0ura0QRlJa:-983383136) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L18)):_
Simplify to `to_run = [ t for t in tests if t.__name__ in filter ]`.
Don't do `a = ...; b = a` -- just decide if you want to name this `to_run` or `tests` aud use that.

---

_[test_sequencer.py, line 20 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lWqUyOehaev_6Uhbb:-K7lWqUzJ0ZgtvJT8dU3:448621521) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L20)):_
If you are using numbers in format strings, you actually don't need the numbers :D -- rewrite to `'=> Going to run {} tests'` (or use names). Applies to the whole file.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by AnotherKamila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

_[test_sequencer.py, line 24 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lXAwaU-QvNDtN1Q2F:-K7lXAwbV2l-9CM-Hw4p:1677371270) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L24)):_
E.g. here names would be better (IIRC `'\t-> [{num}/{total}] {name} ({doc})'.format(num=number, len=len(tests), name=test.__name__, doc=test.__doc__)`).

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by AnotherKamila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

_[test_sequencer.py, line 39 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lXtpSI9QphPaZB66b:-K7lXtpTtivDtwWuIBOS:892648498) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L39)):_
Again, `format()` with a lot of arguments would look better with names.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[test_sequencer.py, line 46 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7l_wacK-87JgZ361Ah:-K7l_wacK-87JgZ361Ai:992196008) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L46)):_
`raw_input()` does not exist in python 3. Use `input()` instead.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by adam-dej** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[test_sequencer.py, line 46 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7l_wacK-87JgZ361Ah:-K7lbNoNg_NLIj3xeg0t:-107756693) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L46)):_
This is python2, and input() in python2 evals it's input as python code.

---

_[test_sequencer.py, line 49 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7lKLDhLGZrLTets9dB:-K7lbdd7f1SS-1q0TzhG:36759499) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L49)):_
That was an attempt to be more explicit about it... will fix

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by AnotherKamila** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[test_sequencer.py, line 46 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7l_wacK-87JgZ361Ah:-K7lcoezjPbay0HPjgCx:-895926332) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L46)):_
And why is this python 2 ? Doesn't your GDB support python 3 ? Maybe you should consider using future.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by adam-dej** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[test_sequencer.py, line 46 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7l_wacK-87JgZ361Ah:-K7leRLZty3EN5Se3K8m:-1009517833) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L46)):_
It doesn't (arm-none-eabi-gdb from arch repos).

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by AnotherKamila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[test_sequencer.py, line 46 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7l_wacK-87JgZ361Ah:-K7loOg42XhFON0cYUCK:-539691226) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L46)):_
@future: why not, but I don't care. LGTM.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Comment by lubo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[test_sequencer.py, line 46 [r1]](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2#-K7l_wacK-87JgZ361Ah:-K7lpIABWyvvKntDFhh-:-1528611336) ([raw file](https://github.com/fmfi-svt-deadlock/hw-testing/blob/60f88e2e90ff411f121236a0e44100ca2022f9bb/test_sequencer.py#L46)):_
Adam said 2to3 will be used if necessary. I'd be happier with future but it's his call. LGTM.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fmfi-svt-deadlock/hw-testing/2)_

**Pull request merged**
